<?php

namespace Kamansoft\Klorchid\Console\Commands;

use Illuminate\Console\Command;
use Orchid\Platform\Commands\ScreenCommand;
use Orchid\Platform\Dashboard;
use Illuminate\Support\Str;

class KlorchidCrudScreenCommand extends ScreenCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'klorchid:make:crud:screen
        {name : The name of the screen class }';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate a new Klorchid Crud Screen';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'KlorchidCrudScreen';


    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    protected function getStub(): string
    {
        //return app_path('Kaman/resources/stubs/keditscreen.stub');
        return __DIR__ . '/../../../resources/stubs/klorchid.multimode.screen.stub';
    }

        /**
     * Get the default namespace for the class.
     *
     * @param string $rootNamespace
     *
     * @return string
     */
    protected function getDefaultNamespace($rootNamespace): string
    {

        $app_name_path = '';
        $path_to_return  = $rootNamespace;

        if ($this->option('useAppNamePath')) {
            $app_name = Str::studly((config('app.name')));
            $app_name_screens_path = '\\'.$app_name.'\Screens';
            $path_to_return = $path_to_return.$app_name_screens_path;
        }else{
            $path_to_return = $path_to_return.'\Screens';
        }

        return $path_to_return;

    }

    protected function replaceClass($stub, $name)
    {
        $stub =  parent::replaceClass($stub, $name); // TODO: Change the autogenerated stub


        $replace = [$this->getModelClassName(),$this->getClassNamespaceFromPath($this->argument('repository'))];
        return str_replace(['DummyRepositoryClassName','DummyRepositoryFullClassName'], $replace, $stub);


    }

    protected function getClassNamespaceFromPath($path){
        return str_replace('/','\\',$path);
    }

    protected function getModelClassName(){
        $model_name = $this->argument('repository');
        $exploded = explode('/',$model_name);
        return end($exploded);
    }


}
